### ISSUE TITLE
Will it work with Object.defineProperty?

### ISSUE THREAD

**Issue by ar2r13** [tibdex/babel-plugin-transform-private-underscore#3]
Will it work with Object.defineProperty(this, '_' + propName || (propName = '_prop'))?
Or with : 
prop = '_prop'
this[prop]

**Comment by tibdex** [comment]
Hi Arthur, sadly it won't work with this kind of dynamic syntax.

You can see [the list of examples](https://github.com/tibdex/babel-plugin-transform-private-underscore/tree/master/examples) tested with the transform. They all access private properties statically.

Dynamic access could work to some extent but it would require additional work to keep track of the property name and it will never but really robust so I prefer no to go down this path.
