### ISSUE TITLE
Doesn't work with stage-2 class property declaration

### ISSUE THREAD

**Issue by ar2r13** [tibdex/babel-plugin-transform-private-underscore#4]
`class Example {
    _property = 3
}`

it transpile to
`class Example {
    constructor() {
        this._property = 3
    }
}`

**Comment by tibdex** [comment]
Hi Arthur,

Yes I know, the plugin only supports ES2016 syntax for now. I wanted to wait for https://github.com/tc39/proposal-private-fields to get accepted before working on supporting the class property declaration syntax you mentioned.

**Comment by tibdex** [comment]
[Private Instance Methods](https://babeljs.io/blog/2018/12/03/7.2.0#private-instance-methods-8654-https-githubcom-babel-babel-pull-8654) should be used instead.
